<?php

namespace app\controllers;

use app\models\car\CarBrands;
use app\models\car\CarModels;
use app\models\car\CarCatalog;
use app\models\car\CarDrives;
use app\models\car\CarEngineTypes;
use app\models\car\SearchCarCatalog;
use Yii;

class CatalogController extends \yii\web\Controller
{
    protected $filters = [];
    protected $brands = [];
    protected $engines = [];
    protected $drives = [];

    protected $searchModel = null;
    protected $dataProvider = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->brands = CarBrands::find()->joinWith('models')->asArray()->all();
        $this->drives = CarDrives::find()->asArray()->all();
        $this->engines = CarEngineTypes::find()->asArray()->all();

        $params = Yii::$app->request->queryParams;
        if (!empty($params['filters'])) {
            $dops = explode(',',$params['filters']);
            if (!empty($dops)) {
                foreach ($dops as $dop) {
                    $dop_param = explode('=',$dop);
                    $params[$dop_param[0] . '_id'] = $dop_param[1];
                }
            }
        }
        $this->filters = $params;
        unset($params['filters']);

        $this->searchModel = new SearchCarCatalog();
        $this->dataProvider = $this->searchModel->search($params);

    }

    public function actionIndex()
    {
        $brand_title = null;
        $model_title = null;
        if ($this->filters['brand_id']) {
            $brand_title = array_filter($this->brands, function($item) {
                return $item['seo_name'] == $this->filters['brand_id'];
            });
        }

        if ($this->filters['model_id']) {
            $model_title = array_filter(current($brand_title)['models'], function($item) {
                return $item['seo_name'] == $this->filters['model_id'];
            });
        }

        $title = 'Продажа автомобилей';
        $title = $title . ((empty( $brand_title)) ? '' :  ' '.current($brand_title)['name']);
        $title = $title . ((empty( $model_title)) ? '' :  ' '.current($model_title)['name']);
        $title = $title . ' в Москве';

        return $this->render('index', [
            'searchModel' => $this->searchModel,
            'dataProvider' => $this->dataProvider,
            'brands' => $this->brands,
            'drives' => $this->drives,
            'engines' => $this->engines,
            'filters' => $this->filters,
            'title' => $title,
            'brand_title' => ((empty( $brand_title)) ? '' :  ' '.current($brand_title)['name']),
            'model_title' => ((empty( $model_title)) ? '' :  ' '.current($model_title)['name']),
        ]);
    }

//    public function actionBrand()
//    {
//        return $this->render('index', [
//            'searchModel' => $this->searchModel,
//            'dataProvider' => $this->dataProvider,
//        ]);
//    }
//
//    public function actionModel()
//    {
//        return $this->render('index', [
//            'searchModel' => $this->searchModel,
//            'dataProvider' => $this->dataProvider,
//        ]);
//    }

}
